Resources:
  MyECSInstance:
    Type: AWS::ECS::Cluster
    Properties: 
      CapacityProviders: 
        - FARGATE
      ClusterName: cf-ecs-clsuter
  MyECSTaskDefintion:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      ContainerDefinitions: 
        - Name: hugo-container
          Image: 350102312519.dkr.ecr.ap-south-1.amazonaws.com/hugo-ecr:1.0.0
          PortMappings: 
          - ContainerPort: 80
            HostPort: 80
      Cpu: .25 vCPU
      Memory: .5 GB
      NetworkMode: awsvpc
      TaskRoleArn: arn:aws:iam::350102312519:role/ecsTaskExecutionRole
  MyECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref MyECSInstance
      DesiredCount: 1
      LaunchType: EC2
      ServiceName: cf-ecs-service
      TaskDefinition: cf-ecs-MyECSTaskDefintion-nXooTbLJmpem    
      NetworkConfiguration: 
          AwsvpcConfiguration: 
              AssignPublicIp: ENABLED
              SecurityGroups: 
                - sg-0168fe3cd24ccfe14
              Subnets: 
                - subnet-188b6273