---
Resources:
  CFBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index1.html
        ErrorDocument: error.html